name: quiz
description: A quiz app in flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html_unescape: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: any

flutter:
  uses-material-design: true